print("")
print("PRINT Command - Syntax: 'print {texthere}' - Prints out a simple statement.")
print("Numbers Command - Syntax: 'x' or 'x + x' - Tells you wether it's a number or an expression.")
print("Name Command - Syntax: 'name' - A simple little test of some Python stuff.")
print("Time & Date Command - Syntax: 'time' - Gives the time and date.")
print("MLG Command - Syntax: 'mlg' - Get ready to get rekt.")
print("ABOUT Command - Syntax: 'about' - Some history on this thing... or something.")
print("COMMANDS Command - Syntax: 'commands' - The commands you can perfor -- wait, why are you reading this if you aready just performed the command?!?")
print("...aaaaaand that's pretty much all this thing does")
print("")
